gateway:
  port: 8225
  buffer-size: 1024
  node-id: "gateway#1"
  report-interval-seconds: 15

kafka:
  bootstrap:
    servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
  input-topic: gps.raw.data.test
  unknown-topic: gps.raw.data.unknown.test
  command-topic: gps.command.to.device.test
  command-response-topic: gps.command.response.test
  send:
    mode: Batch
    batch:
      flush-interval-ms: 100
      unknown-flush-interval-ms: 50000
      max-batch-messages: 500

mp:
  messaging:
    incoming:
      gps-command-to-device:
        connector: smallrye-kafka
        topic: ${kafka.command-topic}
        bootstrap.servers: ${kafka.bootstrap.servers}
        key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
        group.id: ${GATEWAY_SERVICE_GROUP_ID:device-command-consumer-test}
        auto.offset.reset: latest

quarkus:
  redis:
    hosts: redis://localhost:6379
  http:
    port: 8080

api:
  key: APM_vltd_GateWay#1

app:
  version: "1.0.0"
